"""Add created_at column to reminders table

Revision ID: 20772872194e
Revises: fa53de3f97cf
Create Date: 2025-07-17 12:46:00.853749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20772872194e'
down_revision = 'fa53de3f97cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'created_at')
    # ### end Alembic commands ###
