"""Update feedback model with new fields and processed

Revision ID: b248ee7bee97
Revises: 7d85b1d8d842
Create Date: 2025-07-14 00:22:28.959813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b248ee7bee97'
down_revision: Union[str, Sequence[str], None] = '7d85b1d8d842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
